<?php
namespace console\controllers;

use yii\console\Controller;
use common\models\Post;

class HelloController extends Controller{
	public $rev;

	public function options($actionID)
	{
		return ['rev'];  // TODO: Change the autogenerated stub
	}

	public function optionAliases()
	{
		return ['r'=>'rev']; // TODO: Change the autogenerated stub
	}

	public function actionIndex(){//index是默认动作
		//./yii hello/index -r=1
		//./yii hello
		if ($this->rev == 1) {
			echo strrev("Hello World!". "\n");
		} else {
			echo "Hello World \n";
		}
	}
	/*
	public function actionIndex(){//index是默认动作
		//php yii hello/index 或者 php yii hello
		echo "Hello World \n";
	}
	*/

	public function actionList(){
		//php yii hello/list
		$posts = Post::find()->all();
		foreach ($posts as $post)
		{
			echo $post["id"]." - ".$post["title"]."\n";
		}
	}

	public function actionWho($name){
		// ./yii hello/who xiaoqing
		echo "Hello ".$name." \n";
	}

	public function actionBoth($name, $another){
		//./yii hello/both xiaoqing weixin
		echo "Hello ".$name." and ".$another." \n";
	}

	public function actionAll(array $names){
		//./yii hello/all xiaoqing,weixin
		var_dump($names);
	}
}